# Generated by Django 5.2.17 on 2026-08-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("computer science", "Information Technology"),
                    ("accounting", "Accounting and Finance"),
                    ("marketing", "Marketing and Sales"),
                    ("business administration", "Business and Administration"),
                    ("human resource management", "Human Resources"),
                    ("civil engineering", "Civil Engineering"),
                    ("mechanical engineering", "Mechanical Engineering"),
                    ("electrical engineering", "Electrical Engineering"),
                    ("biochemistry", "Science and Laboratory"),
                    ("mass communication", "Media and Communication"),
                    ("economics", "Economics and Research"),
                    ("law", "Legal"),
                    ("education", "Education"),
                ],
                max_length=40,
            ),
        ),
    ]
